import { isValidTitle, isValidId, MAX_TITLE_LENGTH } from '../validation';

describe('isValidTitle', () => {
    test('returns false for empty string', () => {
        expect(isValidTitle('')).toBe(false);
    });

    test('returns false for whitespace-only string', () => {
        expect(isValidTitle('   ')).toBe(false);
    });

    test('returns false for a string exceeding MAX_TITLE_LENGTH', () => {
        expect(isValidTitle('a'.repeat(MAX_TITLE_LENGTH + 1))).toBe(false);
    });

    test('returns true for a valid title', () => {
        expect(isValidTitle('Buy groceries')).toBe(true);
    });

    test('returns true for a title exactly at MAX_TITLE_LENGTH', () => {
        expect(isValidTitle('a'.repeat(MAX_TITLE_LENGTH))).toBe(true);
    });

    test('returns false for non-string values', () => {
        expect(isValidTitle(123)).toBe(false);
        expect(isValidTitle(null)).toBe(false);
        expect(isValidTitle(undefined)).toBe(false);
    });
});

describe('isValidId', () => {
    test('returns false for an arbitrary string', () => {
        expect(isValidId('not-a-uuid')).toBe(false);
    });

    test('returns false for an empty string', () => {
        expect(isValidId('')).toBe(false);
    });

    test('returns false for a UUID v1 (version bit differs)', () => {
        // v1 UUID
        expect(isValidId('550e8400-e29b-11d4-a716-446655440000')).toBe(false);
    });

    test('returns true for a valid UUID v4', () => {
        expect(isValidId('550e8400-e29b-41d4-a716-446655440000')).toBe(true);
    });

    test('returns true for a UUID v4 generated by Utilities.getUuid() format', () => {
        // Standard v4 format
        expect(isValidId('f47ac10b-58cc-4372-a567-0e02b2c3d479')).toBe(true);
    });

    test('returns false for non-string values', () => {
        expect(isValidId(42)).toBe(false);
        expect(isValidId(null)).toBe(false);
    });

    test('returns false for a UUID with SQL injection attempt', () => {
        expect(isValidId("'; DROP TABLE todos; --")).toBe(false);
    });
});
